import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="pt-4 fixed z-30 w-full   bg-black text-white">
          <Navbar></Navbar>
        </div>
        {children}
       <Footer></Footer>
      </body>
    </html>
  );
}
